- name: Install Elasticsearch
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
     - elasticsearch
     - logstash

- name: Install new Elasticsearch configuration file
  template:
    src: ./elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  become: true
  notify:
    - restart elasticsearch

- name: Install new Logstash configuration file
  template:
    src: ./logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  become: true
  notify:
    - restart logstash

- name: Install new rsyslog template file
  template:
    src: 01-json-template.conf.j2
    dest: /etc/rsyslog.d/01-json-template.conf
  become: true
  notify:
    - restart rsyslog

- name: Install new rsyslog output configuration file
  template:
    src: 60-output.conf.j2
    dest: /etc/rsyslog.d/60-output.conf
  become: true
  notify:
    - restart rsyslog

- name: Install rsyslog pipeline configuration file
  template:
    src: ./rsyslog-pipeline.conf.j2
    dest: /etc/logstash/conf.d/rsyslog-pipeline.conf
  become: true
  notify:
    - restart logstash

- name: Enable the Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  become: true

- name: Change group of /var/log/elasticsearch to elasticsearch
  file:
    path: /var/log/elasticsearch
    mode: 0774
    group: elasticsearch
  become: true

- name: Enable the Logstash service
  systemd:
    name: logstash
    enabled: yes
    state: started
  become: true

- name: Install new rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  become: true
  notify:
    - restart rsyslog

- name: Make sure rsyslog is enabled.
  systemd:
    name: rsyslog
    enabled: yes
    state: started
  become: true
