- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install OpenJDK JRE headless
  apt:
    name: openjdk-8-jre-headless
    state: latest
  become: true

- name: Install OpenJDK JRE
  apt:
    name: openjdk-8-jre
    state: latest
  become: true
